file_uploads = On
allow_url_fopen = On
memory_limit = 2024M
upload_max_filesize = 100M
max_execution_time = 60
date.timezone = Europe/Kyiv
post_max_size = 100M
max_input_vars = 35000

[xdebug]
xdebug.mode=debug,develop
xdebug.idekey=phpstorm
xdebug.client_host=host.docker.internal
;xdebug.client_host=172.17.0.1
xdebug.start_with_request=yes
xdebug.client_port=9003
